### ISSUE TITLE
Annotate NCBI Taxonomy identifiers in gene.json

### ISSUE THREAD

**Issue by cthoyt** [bridgedb/data#22]
https://github.com/bridgedb/data/blob/master/gene.json has species-specific mappings

https://github.com/bridgedb/data/blob/ee4ffa579763e34555298b39d75d721b3aa2d674/gene.json#L2-L14

would be nice to include structured identifiers for [NCBI Taxonomy identifiers](https://bioregistry.io/registry/ncbitaxon)

**Comment by egonw** [comment]
Not sure we're ready for this... I actually want to create this from the Zenodo record. What we would need to do first is (design and) put machine readable metadata in that repo to state that information. cc @tabbassidaloii @mkutmon @DeniseSl22

**Comment by egonw** [comment]
Let me come back on this...

**Comment by egonw** [comment]
Done:

![image](https://user-images.githubusercontent.com/26721/212474998-2f52bcf5-5021-4408-bf81-e32a22a9f99b.png)
