### ISSUE TITLE
HS_derby database for genesProteins version108 Ensembl gives error in PV3.3.0

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/data#33]
See printscreen:
![image](https://github.com/user-attachments/assets/e2e2ebe6-f330-4b90-8477-1ecf1cfbfac2)

I downloaded a fresh copy from the website, but it doesn't seem to be compatible @tabbassidaloii @egonw

**Comment by DeniseSl22** [comment]
We're still trying to confirm where this issue is coming from (together with intern from @marvinm2 ). I'll keep you posted!

**Comment by DeniseSl22** [comment]
We Figured it out; PathVisio does not read brackets well in names (of files or folders). I will move this issue to PathVisio.

**Comment by egonw** [comment]
> PathVisio does not read brackets well in names (of files or folders)

Ha, yeah, I had that this weekend with spaces too :/
